language: generic 
sudo: required # docker require sudo permission
services:
  - docker     # tell travis we need a docker container

# any command we can run before we start to deploy our project or do the test
# in this case, we can build our docker image
before_install:
  - docker build . -f Dockerfile.dev -t tsuweiquan/docker-react

# The job to be executed
# -e is extra
# CI=true is used to suppress an exorbitant amount of verbose console outputs 
script:
  - docker run -e CI=true tsuweiquan/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "dockerreact"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-686881272567"
  bucket_path: "dockerreact"
  
  on:
    branch: master
  access_key_id: $aws_access_key
  secret_access_key:
    secure: "$aws_secret_key"
